channels:
  - conda-forge
dependencies:
  - r-base=3.6
  - r-readr
  - r-dplyr
  - r-stringr
  - r-ggraph
  - r-igraph
  - r-ggiraph
  - r-here
  - python=3.9.7
  - numpy
  - pip
  - pycairo
  - pip:
    - coverage
    - detect-secrets==1.0.3
    - myst-parser
    - pre-commit
    - pytest
    - Sphinx
    - toml
    - notebook
    - pandas == 1.3.3
    - python_igraph == 0.9.6
    - matplotlib == 3.4.3
    - bokeh
    - networkx
